type
  InternalError* = object of Exception
